# Generated by Django 4.1.5 on 2023-01-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryy', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='PRACTICES_BUT_INFO/practice/tryy/static/'),
        ),
    ]
