# Generated by Django 4.1.5 on 2023-01-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryy', '0008_rename_password_signup_passsword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Signup',
            name='passsword',
            field=models.CharField(max_length=20),
        ),
    ]
