# Generated by Django 4.1.5 on 2023-01-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryy', '0009_alter_signup_passsword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hi', models.CharField(max_length=50)),
                ('hello', models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
