# Generated by Django 4.1.5 on 2023-01-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryy', '0012_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ketul',
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
