# Generated by Django 4.1.5 on 2023-02-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryy', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='practice/tryy'),
        ),
    ]
