# Generated by Django 4.1.5 on 2023-02-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryy', '0017_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
